blue-badge:
  auth-server:
    url: https://api-internal.${bb_env}.${url}/bb_auth
  messageservice:
    servicehost:
      host: api-internal.${bb_env}.${url}
      port: 443
      scheme: https
      contextpath: /
  la-webapp:
    email-link-uri: https://${email_link_hostname}/set***REMOVED***/
    
  referencedataservice:
    servicehost:
      host: api-internal.${bb_env}.${url}
      port: 443
      scheme: https
      contextpath: /
      
logging:
  level:
    root: ${APP_LOGGING_LEVEL:INFO}
    sample.mybatis.mapper: WARN
    uk.gov.dft.bluebadge.service: ${APP_LOGGING_LEVEL:DEBUG}
    org.springframework.security: INFO

management:
  server:
    port: ${bb_health:8081}

spring:
  main:
    banner-mode: "off"
  datasource:
     ***REMOVED***
    username: ${bb_db_username}
    url: jdbc:postgresql://${RDS_HOSTNAME}:5432/${bb_database}?currentSchema=usermanagement&sslmode=verify-full

server:
  port: ${bb_port:8080}
