blue-badge:
  auth-server:
    url: https://authorisation-service.${bb_env}.${url}/bb_auth
    client-id: bb_user_management_id
     ***REMOVED***
  messageservice:
    servicehost:
      host: messaging-service.${bb_env}.${url}
      port: 443
      scheme: https
      connectiontimeout: 6000
      requesttimeout: 6000
      contextpath: /uk-gov-dft/message-service/1.0.0
  la-webapp:
    email-link-uri: https://la-webapp.${bb_env}.${url}/set***REMOVED***/
    
  referencedataservice:
    servicehost:
      host: reference-service.${bb_env}.${url}
      port: 443
      scheme: https
      connectiontimeout: 6000
      requesttimeout: 6000
      contextpath: /uk-gov-dft/reference-data-service/1.0.0
      
logging:
  level:
    root: ${APP_LOGGING_LEVEL:-INFO}
    uk.gov.dft.bluebadge.service: ${APP_LOGGING_LEVEL:-DEBUG}
    org.springframework.security: INFO

management:
  server:
    port: ${bb_health:-8081}
    servlet:
      context-path: /manage
  endpoints:
    web:
      exposure:
        include: '*'

mybatis:
  type-aliases-package: uk.gov.dft.bluebadge.service.usermanagement.repository.domain

spring:
  datasource:
     ***REMOVED***
    username: ${bb_db_username:-developer}
    url: jdbc:postgresql://postgres-service.${bb_env}.${url}:5432/${bb_database:-bb_dev}?currentSchema=usermanagement
  jackson:
    date-format: uk.gov.dft.bluebadge.common.api.RFC3339DateFormat
    serialization:
      write-dates-as-timestamps: false

server:
  port: ${bb_port:-8080}
  servlet:
    context-path: /uk-gov-dft/user-management-service/1.0.0

springfox.documentation.swagger.v2.path: /api-docs
