blue-badge:
  auth-server:
    url: https://api.${bb_env}.${url}/bb_auth
  messageservice:
    servicehost:
      host: api.${bb_env}.${url}
      port: 443
      scheme: https
      contextpath: /messages1
  la-webapp:
    email-link-uri: https://la-webapp.${bb_env}.${url}/set***REMOVED***/
    
  referencedataservice:
    servicehost:
      host: api.${bb_env}.${url}
      port: 443
      scheme: https
      contextpath: /reference-data1
      
logging:
  level:
    root: ${APP_LOGGING_LEVEL:-INFO}
    sample.mybatis.mapper: WARN
    uk.gov.dft.bluebadge.service: ${APP_LOGGING_LEVEL:-DEBUG}
    org.springframework.security: INFO

management:
  server:
    port: ${bb_health:8081}

spring:
  datasource:
     ***REMOVED***
    username: ${bb_db_username:-developer}
    url: jdbc:postgresql://postgres-service.${bb_env}.${url}:5432/${bb_database}?currentSchema=usermanagement

server:
  port: ${bb_port:8080}



