blue-badge:
  auth-server:
    url: http://localhost:8380/bb_auth
    client-id: bb_user_management_id
     ***REMOVED***
  messageservice:
    servicehost:
      host: localhost
      port: 8480
      scheme: http
      connectiontimeout: 6000
      requesttimeout: 6000
      contextpath: /uk-gov-dft/message-service/1.0.0
  la-webapp:
    email-link-uri: http://localhost:8080/set***REMOVED***/
  reference-data-service:
    service-host:
      host: localhost
      port: 8580
      scheme: http
      connectiontimeout: 6000
      requesttimeout: 6000
      contextpath: /uk-gov-dft/reference-data-service/1.0.0

logging:
  level:
    root: ${APP_LOGGING_LEVEL:-INFO}
    sample.mybatis.mapper: WARN
    uk.gov.dft.bluebadge.service: ${APP_LOGGING_LEVEL:-DEBUG}
    org.springframework.security: DEBUG

management:
  server:
    port: 8181
    servlet:
      context-path: /manage
  endpoints:
    web:
      exposure:
        include: '*'

mybatis:
  type-aliases-package: uk.gov.dft.bluebadge.service.usermanagement.repository.domain

spring:
  datasource:
     ***REMOVED***
    username: developer
    url: jdbc:postgresql://127.0.0.1:5432/bb_dev?currentSchema=usermanagement
  jackson:
    date-format: uk.gov.dft.bluebadge.common.api.RFC3339DateFormat
    serialization:
      write-dates-as-timestamps: false
  profiles:
    active: dev

server:
  port: 8180
  servlet:
    context-path: /uk-gov-dft/user-management-service/1.0.0

springfox.documentation.swagger.v2.path: /api-docs


