blue-badge:
  auth-server:
    url: http://authorisation-service:8080/bb_auth
    client-id: bb_user_management_id
     ***REMOVED***
  messageservice:
    servicehost:
      host: message-service
      port: 8080
  la-webapp:
      email-link-uri: ${LA-WEBAPP_URL}/set***REMOVED***/

logging:
  level:
    root: ${APP_LOGGING_LEVEL:-INFO}
    sample.mybatis.mapper: WARN
    uk.gov.dft.bluebadge.service: ${APP_LOGGING_LEVEL:-DEBUG}

spring:
  datasource:
     ***REMOVED***
    username: developer
    url: jdbc:postgresql://postgresql:5432/bb_dev?currentSchema=usermanagement



