package uk.gov.dft.bluebadge.service.client.messageservice.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import org.springframework.validation.annotation.Validated;

/** PasswordResetRequest */
@Validated
public class PasswordResetRequest {
  @JsonProperty("id")
  private Integer id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("emailAddress")
  private String emailAddress = null;

  @JsonProperty("localAuthorityId")
  private Integer localAuthorityId = null;

  @JsonProperty("isNewUser")
  private Boolean isNewUser = null;

  public PasswordResetRequest id(Integer id) {
    this.id = id;
    return this;
  }

  /**
   * Unique identifier representing a specific user. Autogenerated on create.
   *
   * @return id
   */
  @ApiModelProperty(
    example = "1",
    value = "Unique identifier representing a specific user. Autogenerated on create."
  )
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public PasswordResetRequest name(String name) {
    this.name = name;
    return this;
  }

  /**
   * Users name.
   *
   * @return name
   */
  @ApiModelProperty(example = "Robert Worthington", required = true, value = "Users name.")
  @NotNull
  @Size(max = 100)
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public PasswordResetRequest emailAddress(String emailAddress) {
    this.emailAddress = emailAddress;
    return this;
  }

  /**
   * email address.
   *
   * @return emailAddress
   */
  @ApiModelProperty(
    example = "rob.worthington@norealserver.com",
    required = true,
    value = "email address."
  )
  @NotNull
  public String getEmailAddress() {
    return emailAddress;
  }

  public void setEmailAddress(String emailAddress) {
    this.emailAddress = emailAddress;
  }

  public PasswordResetRequest localAuthorityId(Integer localAuthorityId) {
    this.localAuthorityId = localAuthorityId;
    return this;
  }

  /**
   * Id of Local Authority user belongs to
   *
   * @return localAuthorityId
   */
  @ApiModelProperty(example = "2", value = "Id of Local Authority user belongs to")
  public Integer getLocalAuthorityId() {
    return localAuthorityId;
  }

  public void setLocalAuthorityId(Integer localAuthorityId) {
    this.localAuthorityId = localAuthorityId;
  }

  public PasswordResetRequest isNewUser(Boolean isNewUser) {
    this.isNewUser = isNewUser;
    return this;
  }

  /**
   * true if new user, false if password change
   *
   * @return isNewUser
   */
  @ApiModelProperty(required = true, value = "true if new user, false if password change")
  @NotNull
  public Boolean isIsNewUser() {
    return isNewUser;
  }

  public void setIsNewUser(Boolean isNewUser) {
    this.isNewUser = isNewUser;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PasswordResetRequest passwordResetRequest = (PasswordResetRequest) o;
    return Objects.equals(this.id, passwordResetRequest.id)
        && Objects.equals(this.name, passwordResetRequest.name)
        && Objects.equals(this.emailAddress, passwordResetRequest.emailAddress)
        && Objects.equals(this.localAuthorityId, passwordResetRequest.localAuthorityId)
        && Objects.equals(this.isNewUser, passwordResetRequest.isNewUser);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, emailAddress, localAuthorityId, isNewUser);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PasswordResetRequest {\n");

    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    emailAddress: ").append(toIndentedString(emailAddress)).append("\n");
    sb.append("    localAuthorityId: ").append(toIndentedString(localAuthorityId)).append("\n");
    sb.append("    isNewUser: ").append(toIndentedString(isNewUser)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
