usermanagementservice:
  servicehost:
    host: localhost
    port: 8180
    scheme: http
    connectiontimeout: 6000
    requesttimeout: 6000
    contextpath: /uk-gov-dft/user-management-service/1.0.0

